name: Build HAOS
run-name: Building Mixtile Edge2 Home Assistant Operating System

on:
  workflow_dispatch:

 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get more disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35840
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Free up disk space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet && \
          sudo rm -rf /opt/ghc && \
          sudo rm -rf "/usr/local/share/boost" && \
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" 

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential bison \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev

      - name: Build HAOS
        shell: bash
        run: |
          sed -i 's/-it//g' scripts/enter.sh
          sed -i "s|\${CACHE_DIR:-\$HOME/hassos-cache}|\${CACHE_DIR:-\$(pwd)/hassos-cache}|g" scripts/enter.sh
          ./scripts/enter.sh make -j$(($(nproc) + 1)) mixtile_edge2

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: rk3568-mixtile-edge2-haos.img.xz
          path: output/images/haos_*.img.xz
          if-no-files-found: error

      - name: Clean cache
        shell: bash
        run: sync
